[server]
headless = true
maxUploadSize = 200

[theme]
base = "dark"
primaryColor = "#14B8A6"
backgroundColor = "#071018"
secondaryBackgroundColor = "#0D1722"
textColor = "#E6EDF3"
font = "sans serif"
